version: '3.8'

services:
  app:
    build: 
      context: .      
    environment:
      MONGO_COONECTION_STRING: mongodb://db:27017/jgaad
      JWT_SECRET: "your-secret-key"
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: jgaad